/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IHysteaksBatchSendInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateFee"
      | "fee"
      | "sendERC20Batch"
      | "sendNativeBatch"
      | "setFee"
      | "setFeeExempt"
      | "setFeeExemptBatch"
      | "withdrawERC20Fees"
      | "withdrawNativeFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchFeeExemptSet"
      | "ERC20BatchSent"
      | "ERC20FeesWithdrawn"
      | "FeeExemptSet"
      | "FeeSet"
      | "NativeBatchSent"
      | "NativeFeesWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sendERC20Batch",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sendNativeBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeExempt",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeExemptBatch",
    values: [AddressLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20Fees",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNativeFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendERC20Batch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendNativeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeExempt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeExemptBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20Fees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNativeFees",
    data: BytesLike
  ): Result;
}

export namespace BatchFeeExemptSetEvent {
  export type InputTuple = [recipients: AddressLike[], isExempt: boolean[]];
  export type OutputTuple = [recipients: string[], isExempt: boolean[]];
  export interface OutputObject {
    recipients: string[];
    isExempt: boolean[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20BatchSentEvent {
  export type InputTuple = [
    token: AddressLike,
    recipients: AddressLike[],
    amounts: BigNumberish[]
  ];
  export type OutputTuple = [
    token: string,
    recipients: string[],
    amounts: bigint[]
  ];
  export interface OutputObject {
    token: string;
    recipients: string[];
    amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20FeesWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeExemptSetEvent {
  export type InputTuple = [recipient: AddressLike, isExempt: boolean];
  export type OutputTuple = [recipient: string, isExempt: boolean];
  export interface OutputObject {
    recipient: string;
    isExempt: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeSetEvent {
  export type InputTuple = [fee: BigNumberish];
  export type OutputTuple = [fee: bigint];
  export interface OutputObject {
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeBatchSentEvent {
  export type InputTuple = [recipients: AddressLike[], amounts: BigNumberish[]];
  export type OutputTuple = [recipients: string[], amounts: bigint[]];
  export interface OutputObject {
    recipients: string[];
    amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeFeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IHysteaksBatchSend extends BaseContract {
  connect(runner?: ContractRunner | null): IHysteaksBatchSend;
  waitForDeployment(): Promise<this>;

  interface: IHysteaksBatchSendInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateFee: TypedContractMethod<[amount: BigNumberish], [bigint], "view">;

  fee: TypedContractMethod<[], [bigint], "view">;

  sendERC20Batch: TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  sendNativeBatch: TypedContractMethod<
    [recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "payable"
  >;

  setFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setFeeExempt: TypedContractMethod<
    [recipient: AddressLike, _isExempt: boolean],
    [void],
    "nonpayable"
  >;

  setFeeExemptBatch: TypedContractMethod<
    [recipients: AddressLike[], _isExempt: boolean[]],
    [void],
    "nonpayable"
  >;

  withdrawERC20Fees: TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawNativeFees: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sendERC20Batch"
  ): TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendNativeBatch"
  ): TypedContractMethod<
    [recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeExempt"
  ): TypedContractMethod<
    [recipient: AddressLike, _isExempt: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeExemptBatch"
  ): TypedContractMethod<
    [recipients: AddressLike[], _isExempt: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawERC20Fees"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawNativeFees"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BatchFeeExemptSet"
  ): TypedContractEvent<
    BatchFeeExemptSetEvent.InputTuple,
    BatchFeeExemptSetEvent.OutputTuple,
    BatchFeeExemptSetEvent.OutputObject
  >;
  getEvent(
    key: "ERC20BatchSent"
  ): TypedContractEvent<
    ERC20BatchSentEvent.InputTuple,
    ERC20BatchSentEvent.OutputTuple,
    ERC20BatchSentEvent.OutputObject
  >;
  getEvent(
    key: "ERC20FeesWithdrawn"
  ): TypedContractEvent<
    ERC20FeesWithdrawnEvent.InputTuple,
    ERC20FeesWithdrawnEvent.OutputTuple,
    ERC20FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "FeeExemptSet"
  ): TypedContractEvent<
    FeeExemptSetEvent.InputTuple,
    FeeExemptSetEvent.OutputTuple,
    FeeExemptSetEvent.OutputObject
  >;
  getEvent(
    key: "FeeSet"
  ): TypedContractEvent<
    FeeSetEvent.InputTuple,
    FeeSetEvent.OutputTuple,
    FeeSetEvent.OutputObject
  >;
  getEvent(
    key: "NativeBatchSent"
  ): TypedContractEvent<
    NativeBatchSentEvent.InputTuple,
    NativeBatchSentEvent.OutputTuple,
    NativeBatchSentEvent.OutputObject
  >;
  getEvent(
    key: "NativeFeesWithdrawn"
  ): TypedContractEvent<
    NativeFeesWithdrawnEvent.InputTuple,
    NativeFeesWithdrawnEvent.OutputTuple,
    NativeFeesWithdrawnEvent.OutputObject
  >;

  filters: {
    "BatchFeeExemptSet(address[],bool[])": TypedContractEvent<
      BatchFeeExemptSetEvent.InputTuple,
      BatchFeeExemptSetEvent.OutputTuple,
      BatchFeeExemptSetEvent.OutputObject
    >;
    BatchFeeExemptSet: TypedContractEvent<
      BatchFeeExemptSetEvent.InputTuple,
      BatchFeeExemptSetEvent.OutputTuple,
      BatchFeeExemptSetEvent.OutputObject
    >;

    "ERC20BatchSent(address,address[],uint256[])": TypedContractEvent<
      ERC20BatchSentEvent.InputTuple,
      ERC20BatchSentEvent.OutputTuple,
      ERC20BatchSentEvent.OutputObject
    >;
    ERC20BatchSent: TypedContractEvent<
      ERC20BatchSentEvent.InputTuple,
      ERC20BatchSentEvent.OutputTuple,
      ERC20BatchSentEvent.OutputObject
    >;

    "ERC20FeesWithdrawn(address,address,uint256)": TypedContractEvent<
      ERC20FeesWithdrawnEvent.InputTuple,
      ERC20FeesWithdrawnEvent.OutputTuple,
      ERC20FeesWithdrawnEvent.OutputObject
    >;
    ERC20FeesWithdrawn: TypedContractEvent<
      ERC20FeesWithdrawnEvent.InputTuple,
      ERC20FeesWithdrawnEvent.OutputTuple,
      ERC20FeesWithdrawnEvent.OutputObject
    >;

    "FeeExemptSet(address,bool)": TypedContractEvent<
      FeeExemptSetEvent.InputTuple,
      FeeExemptSetEvent.OutputTuple,
      FeeExemptSetEvent.OutputObject
    >;
    FeeExemptSet: TypedContractEvent<
      FeeExemptSetEvent.InputTuple,
      FeeExemptSetEvent.OutputTuple,
      FeeExemptSetEvent.OutputObject
    >;

    "FeeSet(uint256)": TypedContractEvent<
      FeeSetEvent.InputTuple,
      FeeSetEvent.OutputTuple,
      FeeSetEvent.OutputObject
    >;
    FeeSet: TypedContractEvent<
      FeeSetEvent.InputTuple,
      FeeSetEvent.OutputTuple,
      FeeSetEvent.OutputObject
    >;

    "NativeBatchSent(address[],uint256[])": TypedContractEvent<
      NativeBatchSentEvent.InputTuple,
      NativeBatchSentEvent.OutputTuple,
      NativeBatchSentEvent.OutputObject
    >;
    NativeBatchSent: TypedContractEvent<
      NativeBatchSentEvent.InputTuple,
      NativeBatchSentEvent.OutputTuple,
      NativeBatchSentEvent.OutputObject
    >;

    "NativeFeesWithdrawn(address,uint256)": TypedContractEvent<
      NativeFeesWithdrawnEvent.InputTuple,
      NativeFeesWithdrawnEvent.OutputTuple,
      NativeFeesWithdrawnEvent.OutputObject
    >;
    NativeFeesWithdrawn: TypedContractEvent<
      NativeFeesWithdrawnEvent.InputTuple,
      NativeFeesWithdrawnEvent.OutputTuple,
      NativeFeesWithdrawnEvent.OutputObject
    >;
  };
}
